theme: jekyll-theme-minimal
title: Intro to R
show_downloads: "false"
logo: <img src="images/logo.png" width="50%" height="50%"/>
description: Course page for RECON MSF introduction to R course April 2021
